### ISSUE TITLE
Illegal thread group access

### ISSUE THREAD

**Issue by Soledge** [YoFuzzy3/CommandSync#6]
Plugin performed restricted action, please inform them to use proper API methods: Illegal thread group access
java.security.AccessControlException: Plugin violation: Illegal thread group access
    at net.md_5.bungee.BungeeSecurityManager.checkRestricted(BungeeSecurityManager.java:39)
    at net.md_5.bungee.BungeeSecurityManager.checkAccess(BungeeSecurityManager.java:62)
    at java.lang.ThreadGroup.checkAccess(ThreadGroup.java:315)
    at java.lang.Thread.init(Thread.java:389)
    at java.lang.Thread.init(Thread.java:349)
    at java.lang.Thread.<init>(Thread.java:444)
    at com.fuzzoland.CommandSyncServer.ClientHandler.<init>(ClientHandler.java:25)
    at com.fuzzoland.CommandSyncServer.ClientListener.run(ClientListener.java:20)

**Comment by Soledge** [comment]
this error is followed by this:

11:37:48 [INFO] [CommandSync] Received new connection from localhost.localdomain:50698.
11:37:48 [INFO] [CommandSync] [localhost.localdomain:50698] [Hub] Provided an invalid password.

and my commands wont actually issue.

**Comment by adambkehl** [comment]
Bump.

**Comment by adambkehl** [comment]
@Soledge Dude: 11:37:48 [INFO] [CommandSync] [localhost.localdomain:50698] [Hub] Provided an invalid password. means the password wasn't set correctly in the config of both the server, and the client... It works, but the illegal group access error still appears. Also, please update to the latest and correct ways of doing things. Asynchronous commands aren't allowed.

**Comment by HeroCC** [comment]
Same issue here, it is really annoying.

**Comment by HeroCC** [comment]
Any updates on this?

**Comment by Gregin** [comment]
Same issue here

**Comment by nurdism** [comment]
same issue

**Comment by FarrentFTW** [comment]
Same issue for me too, I need a plugin like this and I can't find one, except this. Really frustrating that it doesn't work.
