### ISSUE TITLE
Plugin performed restricted action, please inform them to use proper API 

### ISSUE THREAD

**Issue by RonaldPhilipsen** [YoFuzzy3/CommandSync#7]
13:43:40 [WARNING] Plugin performed restricted action, please inform them to use proper API methods: Illegal thread group access
java.security.AccessControlException: Plugin violation: Illegal thread group access
    at net.md_5.bungee.BungeeSecurityManager.checkRestricted(BungeeSecurityManager.java:39)
    at net.md_5.bungee.BungeeSecurityManager.checkAccess(BungeeSecurityManager.java:62)
    at java.lang.ThreadGroup.checkAccess(Unknown Source)
    at java.lang.Thread.init(Unknown Source)
    at java.lang.Thread.init(Unknown Source)
    at java.lang.Thread.<init>(Unknown Source)
    at com.fuzzoland.CommandSyncServer.ClientHandler.<init>(ClientHandler.java:25)
    at com.fuzzoland.CommandSyncServer.ClientListener.run(ClientListener.java:20)

**Comment by RonaldPhilipsen** [comment]
this happens right after this btw
13:43:07 [INFO] [CommandSync] Received new connection from 127.0.0.1:65153.
13:43:07 [INFO] [CommandSync] Connection from 127.0.0.1:65153 under name survival has been authorised.

**Comment by FarrentFTW** [comment]
Same.

**Comment by HeroCC** [comment]
Same as #6
